package wscli;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2016-05-05T12:12:43.557+02:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebServiceClient(name = "FindUserService", 
                  wsdlLocation = "http://localhost:8080/ex225/FindUser?wsdl",
                  targetNamespace = "http://ws/") 
public class FindUserService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws/", "FindUserService");
    public final static QName FindUserPort = new QName("http://ws/", "FindUserPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ex225/FindUser?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(FindUserService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ex225/FindUser?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public FindUserService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public FindUserService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FindUserService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FindUserService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FindUserService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public FindUserService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns FindUser
     */
    @WebEndpoint(name = "FindUserPort")
    public FindUser getFindUserPort() {
        return super.getPort(FindUserPort, FindUser.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FindUser
     */
    @WebEndpoint(name = "FindUserPort")
    public FindUser getFindUserPort(WebServiceFeature... features) {
        return super.getPort(FindUserPort, FindUser.class, features);
    }

}
